import type { Metadata } from "next";
import "./globals.css";
import { Unna, Playfair_Display, Mea_Culpa } from "next/font/google";

const unna = Unna({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-unna",
  display: "swap",
})

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-playfair-display",
  display: "swap",
})

const meaCulpa = Mea_Culpa({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mea-culpa",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en h-full"
      className={`${unna.variable} ${playfairDisplay.variable} ${meaCulpa.variable} `}
    >
      <body className="antialiased h-full">{children}</body>
    </html>
  );
}
