services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - gradle-cache:/root/.gradle
      - maven-cache:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"   # app
      - "5005:5005"   # debug (optional)
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      mail:
        condition: service_started
    # By default we keep the container idle; the sail script runs tasks via exec
    command: ["bash", "-lc", "tail -f /dev/null"]

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mail:
    image: axllent/mailpit:latest
    container_name: mail
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI http://localhost:8025

volumes:
  db-data:
  redis-data:
  gradle-cache:
  maven-cache:
