name: Validate Gradle Wrapper

on:
  workflow_call:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/gradle/wrapper/**'
      - '.github/workflows/gradle-wrapper-validation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/gradle/wrapper/**'
      - '.github/workflows/gradle-wrapper-validation.yml'

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./backend/gradlew

      - name: Validate Gradle Wrapper
        working-directory: ./backend
        run: ./gradlew --version
