name: Validate Gradle Wrapper

on:
  workflow_call:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/gradle/wrapper/**'
      - '.github/workflows/gradle-wrapper-validation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/gradle/wrapper/**'
      - '.github/workflows/gradle-wrapper-validation.yml'

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Validate Gradle Wrapper
        working-directory: ./backend
        run: ./gradlew --version
